name: mltools
dependencies:
  - python==3.6.0
  - jupyter
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - click
  - nose
  - pip:
    - mlflow
    - xgboost
    - scikit-sparse
    - pygam
